### ISSUE TITLE
¿Qué lenguaje de programación queremos usar?

### ISSUE THREAD

**Issue by adiazcencillo** [MarioRgzLpz/ArbitrageBets#6]
Antes de comenzar a desarrollar este primer milestone, debemos decidir qué lenguaje queremos usar para desarrollar este proyecto. ¿Tienes alguna idea pensada?

**Comment by MarioRgzLpz** [comment]
Buenas Alberto, pues en principio había pensado en usar Rust puesto que es necesario un gran rendimiento para poder obtener cuanto antes las apuestas ya que estas son volátiles. Además conozco muy poco este lenguaje y me gustaría ampliar mis conocimientos sobre él.

**Comment by adiazcencillo** [comment]
Estupendo! Rust es una gran elección. Dejamos entonces fijado el lenguaje de programación.
